name: keihatsu
description: "A manga + light novel reader built for offline freedom, and a seamless reading experience"
publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2
  shared_preferences: ^2.5.3
  phosphor_flutter: ^2.1.0
  provider: ^6.1.5+1
  http: ^1.2.1
  intl: ^0.19.0
  google_sign_in: ^7.2.0
  image_picker: ^1.2.1
  cached_network_image: ^3.4.1
  # Firebase
  firebase_core: ^3.11.0
  firebase_crashlytics: ^4.3.0
  # Offline & Storage
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.5
  connectivity_plus: ^6.1.1
  path: ^1.9.0
  dio: ^5.7.0
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Code Generation
  build_runner: ^2.4.13
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true

  assets:
    - images/
    - manwhaChps/Chapter 263_ce4c77/
    - manwhaChps/Chapter 264_214655/
    - manwhaChps/Chapter 265_a70526/
    - lib/data/chapters.json
